name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Compile with Maven
        run: mvn compile

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Test with Maven
        run: mvn test --file pom.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v3.0.${{ github.run_number }}
          release_name: Release v3.0.${{ github.run_number }}
          draft: false
          prerelease: false